
name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Use recursive for submodules
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.90.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Push generated doc to Rnssp-rmd-templates
        uses: nkoppel/push-files-to-another-repository@v1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'public/*'
          destination-username: 'cdcgov'
          destination-repository: 'Rnssp-rmd-templates'
          destination-directory: 'docs'
          commit-email: 'roseric_2000@yahoo.fr'
          